services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  healthy:
    image: alpine
    command: echo "All services started and healthy!"
    depends_on:
      mysql:
        condition: service_healthy
